/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BidRouteImport } from './routes/bid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BidIndexRouteImport } from './routes/bid.index'
import { Route as BidNewRouteImport } from './routes/bid.new'
import { Route as BidMyRouteImport } from './routes/bid.my'
import { Route as BidLibraryRouteImport } from './routes/bid.library'

const BidRoute = BidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BidIndexRoute = BidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BidRoute,
} as any)
const BidNewRoute = BidNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BidRoute,
} as any)
const BidMyRoute = BidMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => BidRoute,
} as any)
const BidLibraryRoute = BidLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => BidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bid': typeof BidRouteWithChildren
  '/bid/library': typeof BidLibraryRoute
  '/bid/my': typeof BidMyRoute
  '/bid/new': typeof BidNewRoute
  '/bid/': typeof BidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bid/library': typeof BidLibraryRoute
  '/bid/my': typeof BidMyRoute
  '/bid/new': typeof BidNewRoute
  '/bid': typeof BidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bid': typeof BidRouteWithChildren
  '/bid/library': typeof BidLibraryRoute
  '/bid/my': typeof BidMyRoute
  '/bid/new': typeof BidNewRoute
  '/bid/': typeof BidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bid' | '/bid/library' | '/bid/my' | '/bid/new' | '/bid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bid/library' | '/bid/my' | '/bid/new' | '/bid'
  id:
    | '__root__'
    | '/'
    | '/bid'
    | '/bid/library'
    | '/bid/my'
    | '/bid/new'
    | '/bid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidRoute: typeof BidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bid': {
      id: '/bid'
      path: '/bid'
      fullPath: '/bid'
      preLoaderRoute: typeof BidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bid/': {
      id: '/bid/'
      path: '/'
      fullPath: '/bid/'
      preLoaderRoute: typeof BidIndexRouteImport
      parentRoute: typeof BidRoute
    }
    '/bid/new': {
      id: '/bid/new'
      path: '/new'
      fullPath: '/bid/new'
      preLoaderRoute: typeof BidNewRouteImport
      parentRoute: typeof BidRoute
    }
    '/bid/my': {
      id: '/bid/my'
      path: '/my'
      fullPath: '/bid/my'
      preLoaderRoute: typeof BidMyRouteImport
      parentRoute: typeof BidRoute
    }
    '/bid/library': {
      id: '/bid/library'
      path: '/library'
      fullPath: '/bid/library'
      preLoaderRoute: typeof BidLibraryRouteImport
      parentRoute: typeof BidRoute
    }
  }
}

interface BidRouteChildren {
  BidLibraryRoute: typeof BidLibraryRoute
  BidMyRoute: typeof BidMyRoute
  BidNewRoute: typeof BidNewRoute
  BidIndexRoute: typeof BidIndexRoute
}

const BidRouteChildren: BidRouteChildren = {
  BidLibraryRoute: BidLibraryRoute,
  BidMyRoute: BidMyRoute,
  BidNewRoute: BidNewRoute,
  BidIndexRoute: BidIndexRoute,
}

const BidRouteWithChildren = BidRoute._addFileChildren(BidRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidRoute: BidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
